#ifndef _INIT_H
#define _INIT_H
#define R_MD_STGBOXTYPE_CHKBTN_MIN (1)	
#define R_MD_STGBOXTYPE_CHKBTN_MAX (6)		
#define R_MD_STGBOXTYPE_STSBOX_MIN (7)
#define R_MD_STGBOXTYPE_STSBOX_MAX (10)
#define R_MD_STGBOXTYPE_RDOBTN_MIN (11)
#define R_MD_STGBOXTYPE_RDOBTN_MAX (14)	
#define R_MD_STGLISTLINE_YMAX (339)
#define R_MD_STGLISTLINE_YMIN (59)
#define R_MD_STGLISTLINE_OFFSET (280)
#define R_MD_STGLISTLINE_SWITCH (280)
#define R_MD_STGLISTLEFTCLR_WHT (0)
#define R_MD_STGTRALIGHT_CUR_BLK (1)
#define R_MD_STGTRALIGHT_CUR_WHT (2)
#define R_MD_STGLDANIMST_UP		(1)
#define R_MD_STGLDANIMST_DOWN	(2)	
#define R_MD_STGLDANIMST_UP_INIT	(3)		
#define R_MD_STGLDANIMST_DOWN_INIT	(4)
#define R_MD_STGLDANIMST_RES	(5)

typedef unsigned int UInt16;
typedef unsigned char UInt8;
#endif
